minimum_prek_version = "0.4.11"

[update]
cooldown_days = 7
freeze = true
exclude_tags = ["*-{alpha,beta,rc}*"]

[[repos]]
repo = "builtin"
hooks = [
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "check-case-conflict" },
]

[[repos]]
repo = "https://github.com/mongodb/kingfisher"
rev = "5f6fd97c7f92dd004e9b9f2df12afafa5166834d" # frozen: v2.2.0
hooks = [{ id = "kingfisher-auto" }]

[[repos]]
repo = "https://github.com/zizmorcore/zizmor-pre-commit"
# rev = "e3eebf65325ccc992422292cb7a4baee967cf815" # frozen: v1.26.1
rev = "fa412071e4f5d44d44f9e365f4676f9df92456a2" # frozen: v1.30.1
hooks = [{ id = "zizmor" }]

[[repos]]
repo = "https://github.com/rhysd/actionlint"
rev = "914e7df21a07ef503a81201c76d2b11c789d3fca" # frozen: v1.7.12
hooks = [
  {
    id = "actionlint",
    additional_dependencies = [
      "github.com/wasilibs/go-shellcheck/cmd/shellcheck@4e7020840c303923eb1ab846fc446d77be892570", # v0.11.1
    ],
  },
]
