minimum_prek_version = "0.4.11"

[update]
cooldown_days = 7
freeze = true
exclude_tags = ["*-{alpha,beta,rc}*"]

[[repos]]
repo = "builtin"
hooks = [
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "check-case-conflict" },
]

[[repos]]
repo = "https://github.com/mongodb/kingfisher"
rev = "82d050530cdef9af070b8f9a75701c9c27a948c3" # frozen: v1.113.0
hooks = [{ id = "kingfisher-auto" }]

[[repos]]
repo = "https://github.com/zizmorcore/zizmor-pre-commit"
# rev = "e3eebf65325ccc992422292cb7a4baee967cf815" # frozen: v1.26.1
rev = "451b56af716f9f0d0c2b816503a3fd0cf8b036fa" # frozen: v1.29.0
hooks = [{ id = "zizmor" }]

[[repos]]
repo = "https://github.com/rhysd/actionlint"
rev = "914e7df21a07ef503a81201c76d2b11c789d3fca" # frozen: v1.7.12
hooks = [
  {
    id = "actionlint",
    additional_dependencies = [
      "github.com/wasilibs/go-shellcheck/cmd/shellcheck@4e7020840c303923eb1ab846fc446d77be892570", # v0.11.1
    ],
  },
]
