name: Build container images without keys

on:
  workflow_call:
    inputs:
      git_tag:
        required: false
        type: string

env:
  IMAGE_TAG: zig-keyless

jobs:
  build:
    name: Build
    permissions:
      id-token: write # Use GitHub OIDC provider to generate ephemeral signing keys.
      packages: write # Push container images to ghcr.io.
    runs-on: ubuntu-24.04
    outputs:
      github_repository_lc: ${{ steps.github_repository.outputs.lc }}
      digest: ${{ steps.image_manifest_ghcr.outputs.digest }}
      image_tag: ${{ steps.image_ghcr.outputs.tag }}
    steps:
      - name: Check buildah version
        id: buildah_version
        run: |
          installed_version=$(buildah version --json | jq -r '.version')
          minimum_required_version='1.35.0'
          if dpkg --compare-versions "$installed_version" lt "$minimum_required_version"; then
              printf '%s=%s\n' 'is_old' 'true' >> "$GITHUB_OUTPUT"
          fi

      # Workaround: Ubuntu 24.04 does not have 1.35.0 version of buildah yet. Which introduces annotation support for image manifests.
      - name: Build buildah from sources
        if: ${{ steps.buildah_version.outputs.is_old }}
        env:
          BUILDAH_BRANCH: release-1.42
        run: |
          sudo apt-get -y remove buildah
          sudo apt-get update -y
          sudo apt-get install -y \
              bats \
              btrfs-progs \
              git \
              go-md2man \
              golang \
              libapparmor-dev \
              libglib2.0-dev \
              libgpgme11-dev \
              libseccomp-dev \
              libselinux1-dev \
              make \
              runc \
              skopeo \
              libbtrfs-dev
          git clone --branch "$BUILDAH_BRANCH" --depth 1 --single-branch https://github.com/containers/buildah
          cd buildah
          make
          sudo make install

      - name: Output version of installed buildah
        run: buildah version

      # Workaround for buildah: https://github.com/actions/runner-images/issues/10443
      - name: Workaround for Ubuntu 24.04 LTS
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Install Cosign
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0
        with:
          cosign-release: 'v3.0.3'

      - name: Create a blob
        id: blob
        run: |
          zig_mirror=$(curl -fsSL https://ziglang.org/download/community-mirrors.txt | shuf -n 1)
          zig_version=$(curl -fsSL https://ziglang.org/download/index.json | jq -r '.master.version')
          zig_tarball_x86_64_linux_master="zig-x86_64-linux-${zig_version}.tar.xz"
          curl -fsSL "${zig_mirror}/${zig_tarball_x86_64_linux_master}" -o "$zig_tarball_x86_64_linux_master"
          printf '%s=%s\n' 'zig_tarball_x86_64_linux_master' "$zig_tarball_x86_64_linux_master" >> "$GITHUB_OUTPUT"

      - name: Build a container image
        id: image
        env:
          ZIG_TARBALL: ${{ steps.blob.outputs.zig_tarball_x86_64_linux_master }}
        run: |
          buildah unshare ./zig_container.sh "$ZIG_TARBALL"
          image_id=$(cat ./image_id.txt)
          printf '%s=%s\n' 'id' "$image_id" >> "$GITHUB_OUTPUT"

      - name: Create a image manifest
        id: image_manifest_local
        env:
          MANIFEST_NAME: zig
        run: |
          image_manifest_local_imageid=$(buildah manifest create \
              --annotation \
              "org.opencontainers.image.source=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}" \
              "${GITHUB_REPOSITORY##*/}:${MANIFEST_NAME}")
          printf '%s=%s\n' 'id' "$image_manifest_local_imageid" >> "$GITHUB_OUTPUT"

      - name: Add image into image manifest
        env:
          IMAGE_MANIFEST_LOCAL_ID: ${{ steps.image_manifest_local.outputs.id }}
          IMAGE_ID: ${{ steps.image.outputs.id }}
        run: |
          buildah manifest add "$IMAGE_MANIFEST_LOCAL_ID" "$IMAGE_ID"
          buildah images # DEBUG: List images and image manifests
          buildah manifest inspect "$IMAGE_MANIFEST_LOCAL_ID" # DEBUG: Inspect image manifest

      - name: Login to GHCR.io
        run: |
          # GitHub-hosted runners already have a ${HOME}/.docker/config.json with a credential which has unlimited pull rate and limit on Docker Hub.
          # Append the new credential to the same file and tell buildah and its friends (podman, skopeo etc.) to use it.
          printf '%s' "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "$GITHUB_ACTOR" --password-stdin
          printf '%s=%s\n' 'REGISTRY_AUTH_FILE' "${HOME}/.docker/config.json" >> "$GITHUB_ENV"

      - name: Push image manifest into versioned tag on ghcr.io
        id: image_manifest_ghcr
        env:
          IMAGE_MANIFEST_LOCAL_ID: ${{ steps.image_manifest_local.outputs.id }}
          GIT_TAG: ${{ inputs.git_tag }}
        run: |
          buildah manifest push \
              --digestfile image_manifest_ghcr_digest.txt \
              "$IMAGE_MANIFEST_LOCAL_ID" \
              "docker://ghcr.io/${GITHUB_REPOSITORY,,}/${IMAGE_TAG}:${GIT_TAG}"
          image_manifest_ghcr_digest=$(cat ./image_manifest_ghcr_digest.txt)
          printf '%s=%s\n' 'digest' "$image_manifest_ghcr_digest" >> "$GITHUB_OUTPUT"

      - name: Sign image manifest on ghcr.io
        env:
          IMAGE_MANIFEST_GHCR_DIGEST: ${{ steps.image_manifest_ghcr.outputs.digest }}
        run: |
          cosign sign \
              --recursive \
              --yes \
              "ghcr.io/${GITHUB_REPOSITORY,,}/${IMAGE_TAG}@${IMAGE_MANIFEST_GHCR_DIGEST}"

      - name: Create lowercase version of GITHUB_REPOSITORY as a step output
        id: github_repository
        run: printf '%s=%s\n' 'lc' "${GITHUB_REPOSITORY,,}" >> "$GITHUB_OUTPUT"

      - name: Create image tag as a step output
        id: image_ghcr
        run: printf '%s=%s\n' 'tag' "$IMAGE_TAG" >> "$GITHUB_OUTPUT"

      - name: Generate SBOM in SPDX JSON
        uses: anchore/sbom-action@deef08a0db64bfad603422135db61477b16cef56 # v0.22.1
        with:
          image: ghcr.io/${{ steps.github_repository.outputs.lc }}/${{ steps.image_ghcr.outputs.tag }}@${{ steps.image_manifest_ghcr.outputs.digest }}
          format: spdx-json@2.3
          artifact-name: zig-keyless.spdx.json
          output-file: ./zig-keyless.spdx.json

      - name: Generate SBOM in CycloneDX JSON
        uses: anchore/sbom-action@deef08a0db64bfad603422135db61477b16cef56 # v0.22.1
        with:
          image: ghcr.io/${{ steps.github_repository.outputs.lc }}/${{ steps.image_ghcr.outputs.tag }}@${{ steps.image_manifest_ghcr.outputs.digest }}
          format: cyclonedx-json@1.6
          artifact-name: zig-keyless.cyclonedx.json
          output-file: ./zig-keyless.cyclonedx.json

      - name: Attest SPDX SBOM
        env:
          IMAGE_MANIFEST_GHCR_DIGEST: ${{ steps.image_manifest_ghcr.outputs.digest }}
        run: |
          cosign attest \
              --predicate zig-keyless.spdx.json \
              --type spdxjson \
              --yes \
              "ghcr.io/${GITHUB_REPOSITORY,,}/${IMAGE_TAG}@${IMAGE_MANIFEST_GHCR_DIGEST}"

      - name: Attest CycloneDX SBOM
        env:
          IMAGE_MANIFEST_GHCR_DIGEST: ${{ steps.image_manifest_ghcr.outputs.digest }}
        run: |
          cosign attest \
              --predicate zig-keyless.cyclonedx.json \
              --type cyclonedx \
              --yes \
              "ghcr.io/${GITHUB_REPOSITORY,,}/${IMAGE_TAG}@${IMAGE_MANIFEST_GHCR_DIGEST}"

      - name: Push image manifest into latest tag too
        env:
          IMAGE_MANIFEST_LOCAL_ID: ${{ steps.image_manifest_local.outputs.id }}
        run: |
          buildah manifest push \
              "$IMAGE_MANIFEST_LOCAL_ID" \
              "docker://ghcr.io/${GITHUB_REPOSITORY,,}/${IMAGE_TAG}:latest"

      - name: Logout from ghcr.io
        if: ${{ always() }}
        run: docker logout ghcr.io || true

  provenance:
    name: Generate provenance
    permissions:
      actions: read # for detecting the Github Actions environment.
      id-token: write # for creating OIDC tokens for signing.
      packages: write # for uploading attestations.
    needs:
      - build
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v2.1.0 # https://github.com/slsa-framework/slsa-verifier/issues/12
    with:
      image: ghcr.io/${{ needs.build.outputs.github_repository_lc }}/${{ needs.build.outputs.image_tag }}
      digest: ${{ needs.build.outputs.digest }}
      registry-username: ${{ github.actor }}
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}

  artifact_attestations:
    name: Generate Artifact attestations
    permissions:
      id-token: write # Needed for Artifact attestations.
      attestations: write # Upload to Artifact attestations.
    needs:
      - build
    runs-on: ubuntu-24.04
    outputs:
      artifact_attestation_url: ${{ steps.attest_provenance.outputs.attestation-url }}
      sbom_spdx_attestation_url: ${{ steps.attest_sbom_spdx.outputs.attestation-url }}
      sbom_cyclonedx_attestation_url: ${{ steps.attest_sbom_cyclonedx.outputs.attestation-url }}
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0

      - name: Generate artifact attestation
        id: attest_provenance
        uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3.0.0
        with:
          subject-name: ghcr.io/${{ needs.build.outputs.github_repository_lc }}/${{ needs.build.outputs.image_tag }}
          subject-digest: ${{ needs.build.outputs.digest }}

      - name: Attest SPDX SBOM
        uses: actions/attest-sbom@4651f806c01d8637787e274ac3bdf724ef169f34 # v3.0.0
        id: attest_sbom_spdx
        with:
          subject-name: ghcr.io/${{ needs.build.outputs.github_repository_lc }}/${{ needs.build.outputs.image_tag }}
          subject-digest: ${{ needs.build.outputs.digest }}
          sbom-path: ./zig-keyless.spdx.json/zig-keyless.spdx.json

      - name: Attest CycloneDX SBOM
        uses: actions/attest-sbom@4651f806c01d8637787e274ac3bdf724ef169f34 # v3.0.0
        id: attest_sbom_cyclonedx
        with:
          subject-name: ghcr.io/${{ needs.build.outputs.github_repository_lc }}/${{ needs.build.outputs.image_tag }}
          subject-digest: ${{ needs.build.outputs.digest }}
          sbom-path: ./zig-keyless.cyclonedx.json/zig-keyless.cyclonedx.json

  verify:
    name: Verify
    needs:
      - build
      - provenance
      - artifact_attestations
    runs-on: ubuntu-24.04
    env:
      IMAGE_DIGEST: ${{ needs.build.outputs.digest }}
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0
        with:
          cosign-release: 'v3.0.3'

      - name: Verify image manifest signing with full certificate identity
        run: |
          cosign verify \
              --certificate-identity="${GITHUB_SERVER_URL}/LKHN/sscs-reusable-workflows/.github/workflows/reusable_release_container_keyless.yaml@refs/heads/main" \
              --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
              --output-file cosign_verify_output.log \
              "ghcr.io/${GITHUB_REPOSITORY,,}/${IMAGE_TAG}@${IMAGE_DIGEST}"

      - name: Output verification output # DEBUG
        run: jq '.' cosign_verify_output.log

      - name: Verify image manifest signing with part of certificate identity
        run: |
          cosign verify \
              --certificate-identity-regexp="^${GITHUB_SERVER_URL}/LKHN/sscs-reusable-workflows" \
              --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
              "ghcr.io/${GITHUB_REPOSITORY,,}/${IMAGE_TAG}@${IMAGE_DIGEST}"

      - name: Verify attested SPDX SBOM
        run: |
          cosign verify-attestation \
              --certificate-identity="${GITHUB_SERVER_URL}/LKHN/sscs-reusable-workflows/.github/workflows/reusable_release_container_keyless.yaml@refs/heads/main" \
              --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
              --type spdxjson \
              --output-file cosign_verify_attestation_sbom_spdx_output.log \
              "ghcr.io/${GITHUB_REPOSITORY,,}/${IMAGE_TAG}@${IMAGE_DIGEST}"

      - name: Verify attested CycloneDX SBOM
        run: |
          cosign verify-attestation \
              --certificate-identity="${GITHUB_SERVER_URL}/LKHN/sscs-reusable-workflows/.github/workflows/reusable_release_container_keyless.yaml@refs/heads/main" \
              --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
              --type cyclonedx \
              --output-file cosign_verify_attestation_sbom_cyclonedx_output.log \
              "ghcr.io/${GITHUB_REPOSITORY,,}/${IMAGE_TAG}@${IMAGE_DIGEST}"

      - name: Output verified SPDX SBOM # DEBUG
        run: jq -r '.payload' cosign_verify_attestation_sbom_spdx_output.log | base64 --decode | jq

      - name: Output verified CycloneDX SBOM # DEBUG
        run: jq -r '.payload' cosign_verify_attestation_sbom_cyclonedx_output.log | base64 --decode | jq

      - name: Install SLSA verifier
        uses: slsa-framework/slsa-verifier/actions/installer@ea584f4502babc6f60d9bc799dbbb13c1caa9ee6 # v2.7.1

      - name: Verify Provenance
        run: |
          slsa-verifier verify-image \
              "ghcr.io/${GITHUB_REPOSITORY,,}/${IMAGE_TAG}@${IMAGE_DIGEST}" \
              --print-provenance \
              --source-uri "${GITHUB_SERVER_URL##*/}/${GITHUB_REPOSITORY}"

      - name: Verify Artifact attestation
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_FORCE_TTY: true
        run: |
          gh attestation verify \
              --repo "$GITHUB_REPOSITORY" \
              --signer-repo LKHN/sscs-reusable-workflows \
              --format json \
              "oci://ghcr.io/${GITHUB_REPOSITORY,,}/${IMAGE_TAG}@${IMAGE_DIGEST}"

  release:
    name: Release
    permissions:
      contents: write # Create GitHub Release.
    needs:
      - build
      - provenance
      - artifact_attestations
      - verify
    runs-on: ubuntu-24.04
    env:
      IMAGE_DIGEST: ${{ needs.build.outputs.digest }}
      GIT_TAG: ${{ inputs.git_tag }}
      ARTIFACT_ATTESTATION_URL: ${{ needs.artifact_attestations.outputs.artifact_attestation_url }}
      SBOM_SPDX_ATTESTATION_URL: ${{ needs.artifact_attestations.outputs.sbom_spdx_attestation_url }}
      SBOM_CYCLONEDX_ATTESTATION_URL: ${{ needs.artifact_attestations.outputs.sbom_cyclonedx_attestation_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Write release notes with transparency logs
        run: |
          cat > release_notes.md <<EOF
          - **Workflow Run:** ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}
          - **Artifact Attestations:**
            - Artifact attestation: $ARTIFACT_ATTESTATION_URL
            - SPDX SBOM attestation: $SBOM_SPDX_ATTESTATION_URL
            - CycloneDX SBOM attestation: $SBOM_CYCLONEDX_ATTESTATION_URL
          - **Container Image Digest:**
          \`\`\`
          ghcr.io/${GITHUB_REPOSITORY,,}/${IMAGE_TAG}@${IMAGE_DIGEST}
          \`\`\`
          - **Container Image Tag:**
          \`\`\`
          ghcr.io/${GITHUB_REPOSITORY,,}/${IMAGE_TAG}:${GIT_TAG}
          \`\`\`
          EOF

      - name: Release a container image with Sigstore Bundle SBOM and SLSA provenance
        if: ${{ inputs.git_tag }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create \
              "container_keyless/${GIT_TAG}" \
              --generate-notes \
              --notes-file release_notes.md \
              --title "Release of container images signed without keys (OIDC) $GIT_TAG"
